### ISSUE TITLE
Bug mssql

### ISSUE THREAD

**Issue by Erwann9875** [fmohican/NosRegister#1]
After configuring the config.php when I go to the site I get the following message: Fatal error: Maximum execution time of 30 seconds exceeded in C: \ xampp \ htdocs \ config.php on line 32

**Comment by fmohican** [comment]
you don't config property database connection,
check config again, this error it's called "timeout" you database do not response to your request.

**Comment by Erwann9875** [comment]
Can not connect with an mssql account (sql server connection)
can we connect with the Windows Authentication ?

**Comment by fmohican** [comment]
Nope, you need to connect via user and password not windows auth.

**Comment by Erwann9875** [comment]
When I try to connect to the account I created (sql server authentication) I can not connect to it while I put the same ID I used to create the account

**Comment by Erwann9875** [comment]
Problem solved mssql was configured to connect with windows authentication only it was just enough to go into property

To close and thank you for your help
