### ISSUE TITLE
Bug forgot.php

### ISSUE THREAD

**Issue by Erwann9875** [fmohican/NosRegister#11]
Fatal error: Uncaught Error: Call to undefined function forgotmail() in C:\xampp\htdocs\forgot.php:125 Stack trace: #0 {main} thrown in C:\xampp\htdocs\forgot.php on line 125

**Comment by fmohican** [comment]
well there are real bug, I will fix soon, just wait a few

**Comment by fmohican** [comment]
fixed please re-clone (re-download)

**Comment by Erwann9875** [comment]
Tanks !
