### ISSUE TITLE
Something went wrong while connecting to MSSQL

### ISSUE THREAD

**Issue by RiverCZE** [fmohican/NosRegister#18]
how  i connect to sqlsrv please help me 

<?php
$dbhostname = "127.0.0.1"; //MsSQl Server Addres
$db = array(
    "Database" => "opennos", // Database Name
    "Uid" => "river", //Database User
    "PWD" => "riverguns" // Database Password;
);

**Comment by Erwann9875** [comment]
Seriously use extension sql server go readme.de !

**Comment by RiverCZE** [comment]
site wont connect to sql server i have all extensions

**Comment by Erwann9875** [comment]
ACTIVATE THE CONNEXION FOR SQL SERVER

**Comment by RiverCZE** [comment]
where i activate it ?
