### ISSUE TITLE
Forum ?

### ISSUE THREAD

**Issue by Erwann9875** [fmohican/NosRegister#2]
Hello, would you be able to encode a forum for the emulator opennos? thank you in advance
Ps: If you say no it does not matter I know that coding is very long

**Comment by fmohican** [comment]
Actually this its only a register page with some addition (like download links).
Probability will make an CMS (principal website + forum + ticketsystem), but i don't know when.

So for a moment, i'm too busy with my thing (real life thing) and i don't have enghout time for all, but i will try.
Feel free to replay me, if you do not replay i will close issues in 48h after my anwser.
