### ISSUE TITLE
Add ban ip 

### ISSUE THREAD

**Issue by Erwann9875** [fmohican/NosRegister#20]
Add on index.php on ligne 3 
if($_SERVER["REMOTE_ADDR"] == 'IP') header('Location: http://youtube.com');

**Comment by fmohican** [comment]
huh?!!!!!!!! why ?

**Comment by Erwann9875** [comment]
Just one proposition

**Comment by fmohican** [comment]
Hmm i will see.... We need to make Admin Control Panel for that feature... and this it's just an register page ....
Well i will trink about that.
Thanks you.
