### ISSUE TITLE
another problem

### ISSUE THREAD

**Issue by RiverCZE** [fmohican/NosRegister#23]
require_once('config.php'); if(!isset($_COOKIE['passkey'])) setcookie("passkey", "", time()-3600); $secret = rand(1, 100) . rand(1, 100) . rand(1, 100) . rand(1, 100) . rand(1, 100) . rand(1, 100) . rand(1, 100) . $title . rand(1,100); $secret = hash("sha512", $secret); setcookie("passkey", $secret); $headers = apache_request_headers(); if(isset($headers['If-Modified-Since'])) { if(strtotime($headers['If-Modified-Since']) < time() - 43200) { header('HTTP/1.1 304 Not Modified'); Header("Cache-Control: private"); exit; } } ?> # #

**Comment by fmohican** [comment]
huh? more explication then my code ?

**Comment by RiverCZE** [comment]
now its working then i edit sqlserver connection code for xampp

**Comment by fmohican** [comment]
;)

**Comment by RiverCZE** [comment]
your site is best and help me thx

**Comment by RiverCZE** [comment]
look http://89.203.249.100:81/

**Comment by RiverCZE** [comment]
**can i upload edited files with xamp ?**

**Comment by fmohican** [comment]
sure
