### ISSUE TITLE
NosRegister Db Problem

### ISSUE THREAD

**Issue by senterol** [fmohican/NosRegister#26]
I install the registration page and if i try to login with an account created with navicat it works but, if i try to create an account after  the mex "Welcome senterol ! Your account was created." i can't find the new account in the Db. How i can fixx that?

**Comment by fmohican** [comment]
you don't config corectly or you don't have install SQL_SVR :( sadly

**Comment by Erwann9875** [comment]
Easy ! Configure your account mssql all right
