### ISSUE TITLE
Fatal error: Invalid handle returned. in C:\xampp\htdocs\news\index\config.php on line 13

### ISSUE THREAD

**Issue by Brvortex** [fmohican/NosRegister#29]
How can I fix that? Fatal error: Invalid handle returned. in C:\xampp\htdocs\news\index\config.php on line 13

**Comment by Erwann9875** [comment]
Do you have to install mssql driver? That fmohican has put in the readme.de ?
Otherwise install the version 7.*.* of PHP

**Comment by fmohican** [comment]
@Brvortex did you read "readme.md" ?
you did install mssql coreclty or you don't have right php version.
