### ISSUE TITLE
Database register problem

### ISSUE THREAD

**Issue by Erwann9875** [fmohican/NosRegister#4]
Hello, when we register via the website our account does not create in the db why?

**Comment by fmohican** [comment]
Did you setup right?

**Comment by Erwann9875** [comment]
No, sorry 
Problem solved

**Comment by Erwann9875** [comment]
It's not fixed I activated all rights

**Comment by fmohican** [comment]
can provide some screenshot

**Comment by fmohican** [comment]
"Fatal error: Uncaught RuntimeException: No secret provided in bla bla ...."
$usecaptcha = false; //if you want to use google captcha you can get secret key and public key there https://www.google.com/recaptcha/admin
$captchapublickey = ""; //If yes , put your PUBLIC key there  (site key its called on google page's)
$captchasecret = ""; //If yes, put your SECRET key there

**Comment by Erwann9875** [comment]
Screen : http://hpics.li/85f7f70

**Comment by fmohican** [comment]
did you configurate userlogin right? do you try to do test query via php?

**Comment by Erwann9875** [comment]
Hello, I have configured the rights for the user but its not working and I made a request I can connect to the database to give ...

**Comment by fmohican** [comment]
Ok lets see what its the problem
Download this : https://mab.to/TEsKUHN9E , put in your "www" folder (where you have my script configurated, in same folder with index.php, config.php etc...) , after you put script there access your files with http://yourdomainor.ip/debug.php , copy all and post there.

**Comment by Erwann9875** [comment]
When I go on the debug.php I get its Account in DB: 4
==========================================
Trying to add demo account
user: demo
pass: demo
============
Okey Lets see if you got more account in db's
========================================
Account in DB: 4 if anything its all right now you need to see +1 account in DB's like above +1
DO NOT REFRESH THIS PAGE PLEASE! YOU WILL ADD MORE DEMO ACCOUNT TO DATABASE!
post this on github issuess

**Comment by fmohican** [comment]
yap your user do not have enough permissions to execute query, as you can see before script execute you have 4 account, and after script execute you still 4 account on DB.
script work right, i don't know what it's the problem, just try to check permissions...

download navicat, connect using user and password from config and try to run this Query

`
INSERT INTO Account (Authority, Email, LastCompliment, LastSession, Name, Password, RegistrationIP, VerificationToken) VALUES ('1', 'demo@domain.com', '2016-12-29 23:59:11.000', '91', 'demo', '26c669cd0814ac40e5328752b21c4aa6450d16295e4eec30356a06a911c23983aaebe12d5da38eeebfc1b213be650498df8419194d5a26c7e0a50af156853c79', '127.0.0.1', 'fe01ce2a7fbac8fafaed7c982a04e229');
`

**Comment by Erwann9875** [comment]
When I execute the request I get this message Msg 242, Level 16, State 3, Line 3
Converting a varchar data type to a datetime data type has created an out-of-bounds value.
The instruction was stopped.

**Comment by Erwann9875** [comment]
I managed to execute the request from the account that I use for the registration site the account is well created but shows from the registration site sa does not create

**Comment by Erwann9875** [comment]
Hello, I found the problem that came from the account I had created I delete it and recreates with ALL permissions and now the accounts are created in database tanks for help #Close
