### ISSUE TITLE
Mail server 

### ISSUE THREAD

**Issue by Erwann9875** [fmohican/NosRegister#8]
How is one supposed to configure its https://github.com/hmailserver/hmailserver/

**Comment by fmohican** [comment]
https://www.hmailserver.com/download
download install
after install go to hMailServer Administrator > put your password > Settings > Advanced > IP Ranges > My computer , and mark box fallow this screenshot. Enjoy you'r mail server are ready.
![hmail](https://cloud.githubusercontent.com/assets/8583317/21643987/e28a856e-d293-11e6-810b-49f867e8f504.png)

**Comment by Erwann9875** [comment]
ADO: Failed to open the database "opennos" requested by the connection. The connection failed.

**Comment by Erwann9875** [comment]
Database version could not be detected.

**Comment by fmohican** [comment]
wait what? you need to setup separate database for mail server. **DO NOT USER OPENNOS DB FOR MAIL SERVER**

**Comment by Erwann9875** [comment]
If I do not configure a database I do not have access to hmailserver Admin

**Comment by Erwann9875** [comment]
![image](https://cloud.githubusercontent.com/assets/20739405/21649497/33e18be8-d2a2-11e6-915e-3f19b1663ef2.png)

**Comment by fmohican** [comment]
let's make it clear,
you have an SQL server with 2 Database and 2 Users
1 Database and 1 User for OpenNos Emulator and Websites
1 Database and 1 User for hMailServer

you do that?

**Comment by fmohican** [comment]
like that
![nai](https://cloud.githubusercontent.com/assets/8583317/21649776/81a8c590-d2ab-11e6-9566-cf21fa87da78.jpg)

**Comment by Erwann9875** [comment]
Excuse me but I can not find an SSL certificate or could I download it?

**Comment by fmohican** [comment]
you need to make one, fallow steps from readme

**Comment by fmohican** [comment]
but you no need SSL for mail, SSL are optional.

**Comment by Erwann9875** [comment]
After having everything configured it still does not work .. what to do?
![image](https://cloud.githubusercontent.com/assets/20739405/21654223/e663eef2-d2b4-11e6-8a6c-b50cfd9567c4.png)

**Comment by fmohican** [comment]
what i told you? go to Advanced > IP Ranges > My Computer
[this](https://cloud.githubusercontent.com/assets/8583317/21643987/e28a856e-d293-11e6-810b-49f867e8f504.png)

and you certificat are not valide, Private Key must have extension .key and Cerificate .crt

**Comment by Erwann9875** [comment]
Thanks bug solved
