### ISSUE TITLE
Mssql

### ISSUE THREAD

**Issue by Erwann9875** [fmohican/NosRegister#9]
How to connect to mssql remotely?

**Comment by fmohican** [comment]
enter the serverip on 
`$dbhostname = ""; //MsSQl Server Addres`
you may use XX.XX.XX.XX/MSSQL or something like that search on google.... you can find better anwser.

**Comment by Erwann9875** [comment]
Her put me that the request is too long

**Comment by fmohican** [comment]
well, i do some research, you need to enable remote connection on SQL server, just search on google and you will find something.

there are what you need -> https://goo.gl/RuL5td
